// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"why-sys/internal/data/ent/predicate"
	"why-sys/internal/data/ent/role"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleUpdate is the builder for updating Role entities.
type RoleUpdate struct {
	config
	hooks    []Hook
	mutation *RoleMutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (ru *RoleUpdate) Where(ps ...predicate.Role) *RoleUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRoleName sets the "role_name" field.
func (ru *RoleUpdate) SetRoleName(s string) *RoleUpdate {
	ru.mutation.SetRoleName(s)
	return ru
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (ru *RoleUpdate) SetNillableRoleName(s *string) *RoleUpdate {
	if s != nil {
		ru.SetRoleName(*s)
	}
	return ru
}

// SetRoleDesc sets the "role_desc" field.
func (ru *RoleUpdate) SetRoleDesc(s string) *RoleUpdate {
	ru.mutation.SetRoleDesc(s)
	return ru
}

// SetNillableRoleDesc sets the "role_desc" field if the given value is not nil.
func (ru *RoleUpdate) SetNillableRoleDesc(s *string) *RoleUpdate {
	if s != nil {
		ru.SetRoleDesc(*s)
	}
	return ru
}

// ClearRoleDesc clears the value of the "role_desc" field.
func (ru *RoleUpdate) ClearRoleDesc() *RoleUpdate {
	ru.mutation.ClearRoleDesc()
	return ru
}

// Mutation returns the RoleMutation object of the builder.
func (ru *RoleUpdate) Mutation() *RoleMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoleUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoleUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoleUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RoleUpdate) check() error {
	if v, ok := ru.mutation.RoleName(); ok {
		if err := role.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "role_name", err: fmt.Errorf(`ent: validator failed for field "Role.role_name": %w`, err)}
		}
	}
	return nil
}

func (ru *RoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if value, ok := ru.mutation.RoleDesc(); ok {
		_spec.SetField(role.FieldRoleDesc, field.TypeString, value)
	}
	if ru.mutation.RoleDescCleared() {
		_spec.ClearField(role.FieldRoleDesc, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RoleUpdateOne is the builder for updating a single Role entity.
type RoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleMutation
}

// SetRoleName sets the "role_name" field.
func (ruo *RoleUpdateOne) SetRoleName(s string) *RoleUpdateOne {
	ruo.mutation.SetRoleName(s)
	return ruo
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (ruo *RoleUpdateOne) SetNillableRoleName(s *string) *RoleUpdateOne {
	if s != nil {
		ruo.SetRoleName(*s)
	}
	return ruo
}

// SetRoleDesc sets the "role_desc" field.
func (ruo *RoleUpdateOne) SetRoleDesc(s string) *RoleUpdateOne {
	ruo.mutation.SetRoleDesc(s)
	return ruo
}

// SetNillableRoleDesc sets the "role_desc" field if the given value is not nil.
func (ruo *RoleUpdateOne) SetNillableRoleDesc(s *string) *RoleUpdateOne {
	if s != nil {
		ruo.SetRoleDesc(*s)
	}
	return ruo
}

// ClearRoleDesc clears the value of the "role_desc" field.
func (ruo *RoleUpdateOne) ClearRoleDesc() *RoleUpdateOne {
	ruo.mutation.ClearRoleDesc()
	return ruo
}

// Mutation returns the RoleMutation object of the builder.
func (ruo *RoleUpdateOne) Mutation() *RoleMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (ruo *RoleUpdateOne) Where(ps ...predicate.Role) *RoleUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RoleUpdateOne) Select(field string, fields ...string) *RoleUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Role entity.
func (ruo *RoleUpdateOne) Save(ctx context.Context) (*Role, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoleUpdateOne) SaveX(ctx context.Context) *Role {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RoleUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoleUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RoleUpdateOne) check() error {
	if v, ok := ruo.mutation.RoleName(); ok {
		if err := role.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "role_name", err: fmt.Errorf(`ent: validator failed for field "Role.role_name": %w`, err)}
		}
	}
	return nil
}

func (ruo *RoleUpdateOne) sqlSave(ctx context.Context) (_node *Role, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Role.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role.FieldID)
		for _, f := range fields {
			if !role.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != role.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.RoleDesc(); ok {
		_spec.SetField(role.FieldRoleDesc, field.TypeString, value)
	}
	if ruo.mutation.RoleDescCleared() {
		_spec.ClearField(role.FieldRoleDesc, field.TypeString)
	}
	_node = &Role{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
