// Code generated by ent, DO NOT EDIT.

package ent

import (
	"why-sys/internal/data/ent/menu"
	"why-sys/internal/data/ent/role"
	"why-sys/internal/data/ent/schema"
	"why-sys/internal/data/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescMenuName is the schema descriptor for menu_name field.
	menuDescMenuName := menuFields[0].Descriptor()
	// menu.MenuNameValidator is a validator for the "menu_name" field. It is called by the builders before save.
	menu.MenuNameValidator = menuDescMenuName.Validators[0].(func(string) error)
	// menuDescLeaf is the schema descriptor for leaf field.
	menuDescLeaf := menuFields[1].Descriptor()
	// menu.DefaultLeaf holds the default value on creation for the leaf field.
	menu.DefaultLeaf = menuDescLeaf.Default.(bool)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[2].Descriptor()
	// menu.PathValidator is a validator for the "path" field. It is called by the builders before save.
	menu.PathValidator = menuDescPath.Validators[0].(func(string) error)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[3].Descriptor()
	// menu.ComponentValidator is a validator for the "component" field. It is called by the builders before save.
	menu.ComponentValidator = menuDescComponent.Validators[0].(func(string) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescRoleName is the schema descriptor for role_name field.
	roleDescRoleName := roleFields[0].Descriptor()
	// role.RoleNameValidator is a validator for the "role_name" field. It is called by the builders before save.
	role.RoleNameValidator = roleDescRoleName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[0].Descriptor()
	// user.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[2].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(uint8) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
}
