// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.2
// source: auth/v1/auth_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthError int32

const (
	AuthError_USERNAME_IS_EMPTY          AuthError = 0
	AuthError_PASSWORD_IS_EMPTY          AuthError = 1
	AuthError_USERNAME_OR_PASSWORD_ERROR AuthError = 2
	AuthError_USER_NOT_EXIST             AuthError = 3
	AuthError_USER_NOT_VALID             AuthError = 4
)

// Enum value maps for AuthError.
var (
	AuthError_name = map[int32]string{
		0: "USERNAME_IS_EMPTY",
		1: "PASSWORD_IS_EMPTY",
		2: "USERNAME_OR_PASSWORD_ERROR",
		3: "USER_NOT_EXIST",
		4: "USER_NOT_VALID",
	}
	AuthError_value = map[string]int32{
		"USERNAME_IS_EMPTY":          0,
		"PASSWORD_IS_EMPTY":          1,
		"USERNAME_OR_PASSWORD_ERROR": 2,
		"USER_NOT_EXIST":             3,
		"USER_NOT_VALID":             4,
	}
)

func (x AuthError) Enum() *AuthError {
	p := new(AuthError)
	*p = x
	return p
}

func (x AuthError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthError) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_error_proto_enumTypes[0].Descriptor()
}

func (AuthError) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_error_proto_enumTypes[0]
}

func (x AuthError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthError.Descriptor instead.
func (AuthError) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_error_proto_rawDescGZIP(), []int{0}
}

var File_auth_v1_auth_error_proto protoreflect.FileDescriptor

var file_auth_v1_auth_error_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x87, 0x01, 0x0a, 0x09, 0x41, 0x75, 0x74,
	0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41,
	0x4d, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x49, 0x53, 0x5f, 0x45, 0x4d, 0x50,
	0x54, 0x59, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41, 0x4d, 0x45,
	0x5f, 0x4f, 0x52, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x04, 0x1a, 0x04, 0xa0, 0x45,
	0xf4, 0x03, 0x42, 0x18, 0x5a, 0x16, 0x77, 0x68, 0x79, 0x2d, 0x73, 0x79, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_v1_auth_error_proto_rawDescOnce sync.Once
	file_auth_v1_auth_error_proto_rawDescData = file_auth_v1_auth_error_proto_rawDesc
)

func file_auth_v1_auth_error_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_error_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_auth_error_proto_rawDescData)
	})
	return file_auth_v1_auth_error_proto_rawDescData
}

var file_auth_v1_auth_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_auth_error_proto_goTypes = []any{
	(AuthError)(0), // 0: auth.v1.AuthError
}
var file_auth_v1_auth_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_error_proto_init() }
func file_auth_v1_auth_error_proto_init() {
	if File_auth_v1_auth_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_auth_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_auth_error_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_error_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_error_proto_enumTypes,
	}.Build()
	File_auth_v1_auth_error_proto = out.File
	file_auth_v1_auth_error_proto_rawDesc = nil
	file_auth_v1_auth_error_proto_goTypes = nil
	file_auth_v1_auth_error_proto_depIdxs = nil
}
