// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.2
// source: auth/v1/permission.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantRolePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId        uint64   `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	PermissionIds []uint64 `protobuf:"varint,2,rep,packed,name=permissionIds,proto3" json:"permissionIds,omitempty"`
}

func (x *GrantRolePermissionRequest) Reset() {
	*x = GrantRolePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_permission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRolePermissionRequest) ProtoMessage() {}

func (x *GrantRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_permission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*GrantRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *GrantRolePermissionRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GrantRolePermissionRequest) GetPermissionIds() []uint64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type GrantRolePermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GrantRolePermissionResponse) Reset() {
	*x = GrantRolePermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_permission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantRolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRolePermissionResponse) ProtoMessage() {}

func (x *GrantRolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_permission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRolePermissionResponse.ProtoReflect.Descriptor instead.
func (*GrantRolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *GrantRolePermissionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_auth_v1_permission_proto protoreflect.FileDescriptor

var file_auth_v1_permission_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5a, 0x0a, 0x1a, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0d,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x2f, 0x0a,
	0x1b, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa5,
	0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x96, 0x01,
	0x0a, 0x13, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x3a, 0x01, 0x2a, 0x22, 0x29, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x2d, 0x72, 0x6f, 0x6c, 0x65, 0x2d, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x18, 0x5a, 0x16, 0x77, 0x68, 0x79, 0x2d, 0x73, 0x79,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_v1_permission_proto_rawDescOnce sync.Once
	file_auth_v1_permission_proto_rawDescData = file_auth_v1_permission_proto_rawDesc
)

func file_auth_v1_permission_proto_rawDescGZIP() []byte {
	file_auth_v1_permission_proto_rawDescOnce.Do(func() {
		file_auth_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_permission_proto_rawDescData)
	})
	return file_auth_v1_permission_proto_rawDescData
}

var file_auth_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_permission_proto_goTypes = []any{
	(*GrantRolePermissionRequest)(nil),  // 0: auth.v1.GrantRolePermissionRequest
	(*GrantRolePermissionResponse)(nil), // 1: auth.v1.GrantRolePermissionResponse
}
var file_auth_v1_permission_proto_depIdxs = []int32{
	0, // 0: auth.v1.Permission.GrantRolePermission:input_type -> auth.v1.GrantRolePermissionRequest
	1, // 1: auth.v1.Permission.GrantRolePermission:output_type -> auth.v1.GrantRolePermissionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_permission_proto_init() }
func file_auth_v1_permission_proto_init() {
	if File_auth_v1_permission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_v1_permission_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GrantRolePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_permission_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GrantRolePermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_permission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_permission_proto_goTypes,
		DependencyIndexes: file_auth_v1_permission_proto_depIdxs,
		MessageInfos:      file_auth_v1_permission_proto_msgTypes,
	}.Build()
	File_auth_v1_permission_proto = out.File
	file_auth_v1_permission_proto_rawDesc = nil
	file_auth_v1_permission_proto_goTypes = nil
	file_auth_v1_permission_proto_depIdxs = nil
}
